/**
 * Object storage (ADR-0017): an S3-compatible store (the shared RustFS) behind one small
 * interface. RustFS stays private: browsers only get short-lived presigned URLs, rewritten to
 * same-origin `/media/<bucket>/<key>` paths that the web app's Caddy proxies to RustFS with
 * the internal Host header the signature was made for.
 */

export type BucketRole = 'media' | 'uploads' | 'content';

export interface StoredObject {
  size: number;
  contentType: string | null;
}

export interface UploadPart {
  partNumber: number;
  etag: string;
}

export interface ObjectStorage {
  put(
    bucket: BucketRole,
    key: string,
    body: Uint8Array,
    contentType: string
  ): Promise<void>;
  get(bucket: BucketRole, key: string): Promise<Uint8Array | null>;
  head(bucket: BucketRole, key: string): Promise<StoredObject | null>;
  delete(bucket: BucketRole, key: string): Promise<void>;
  /** Same-origin URL to read an object for `seconds`. */
  presignGet(bucket: BucketRole, key: string, seconds?: number): Promise<string>;
  /** Same-origin URL to upload one object (up to a few hundred MB) with PUT. */
  presignPut(
    bucket: BucketRole,
    key: string,
    contentType: string,
    seconds?: number
  ): Promise<string>;
  /** Multipart upload for large files: start, presign each part, complete or abort. */
  createMultipartUpload(
    bucket: BucketRole,
    key: string,
    contentType: string
  ): Promise<string>;
  presignUploadPart(
    bucket: BucketRole,
    key: string,
    uploadId: string,
    partNumber: number,
    seconds?: number
  ): Promise<string>;
  /** Parts already stored (to resume after a network drop). */
  listParts(bucket: BucketRole, key: string, uploadId: string): Promise<UploadPart[]>;
  completeMultipartUpload(
    bucket: BucketRole,
    key: string,
    uploadId: string,
    parts: UploadPart[]
  ): Promise<void>;
  abortMultipartUpload(bucket: BucketRole, key: string, uploadId: string): Promise<void>;
}

/** Presigned URLs live 15 minutes by default (ADR-0017). */
export const PRESIGN_SECONDS = 15 * 60;
/** Browsers upload large files in parts of this size. */
export const PART_SIZE = 32 * 1024 * 1024;
/** Where Caddy serves the store (see infra/caddy/Caddyfile). */
export const MEDIA_PREFIX = '/media';

/**
 * `http://srv-captain--rustfs:9000/suffa-media/a/b.mp4?X-Amz-…` → `/media/suffa-media/a/b.mp4?X-Amz-…`.
 * Only URLs of the configured endpoint are rewritten; anything else is a bug.
 */
export function toMediaPath(presigned: string, endpoint: string): string {
  const url = new URL(presigned);
  const base = new URL(endpoint);
  if (url.origin !== base.origin) {
    throw new Error(`presigned URL for ${url.origin}, expected ${base.origin}`);
  }
  return `${MEDIA_PREFIX}${url.pathname}${url.search}`;
}

/** Object keys are generated by the server; this guards against anything else. */
export function isSafeKey(key: string): boolean {
  return (
    key.length > 0 &&
    key.length <= 512 &&
    /^[A-Za-z0-9!_.*'()/-]+$/.test(key) &&
    !key.startsWith('/') &&
    !key.split('/').some((part) => part === '' || part === '.' || part === '..')
  );
}
