/**
 * The publisher's page-by-page videos (generated by tools/content/publisher-video-index.mjs)
 * and the book pages of each unit (content/sources/book1-pages.json). Only ids, titles and
 * page numbers: the videos are embedded with YouTube's player (ADR-0023).
 */
export interface BookVideo {
  /** YouTube video id. */
  id: string;
  /** Book page the video explains. */
  page: number;
  title: string;
  /** Page placed between playlist neighbours (the title names no page). */
  approx?: boolean;
}

export interface BookVideoIndex {
  source: { publisher: string; playlist: string; rights: string; retrieved: string };
  book: number;
  videos: BookVideo[];
}

export interface BookPages {
  book: number;
  /** "estimated" until the start pages were checked against the printed book. */
  status: 'estimated' | 'verified';
  lastPage: number;
  /** Unit number (as string key) → first book page of that unit. */
  unitStartPages: Record<string, number>;
}

export interface UnitVideos {
  unit: number;
  from: number;
  to: number;
  estimated: boolean;
  videos: BookVideo[];
}
