/**
 * Index of the publisher's official audio (generated by tools/content/publisher-audio-index.mjs).
 * Only titles and links: the audio is streamed from the publisher's server (ADR-0023).
 */
export type AudioTrackKind =
  | 'dialogue'
  | 'vocabulary'
  | 'exercise-example'
  | 'exercise'
  | 'listening'
  | 'sounds'
  | 'exam'
  | 'other';

export interface AudioTrack {
  n: number;
  /** Arabic title as published, e.g. "الحوار الأول (أ)". */
  title: string;
  kind: AudioTrackKind;
  url: string;
}

export interface AudioLesson {
  lesson: number;
  title: string;
  tracks: AudioTrack[];
}

export interface AudioUnit {
  unit: number;
  title: string;
  kind: 'unit' | 'exam';
  lessons: AudioLesson[];
}

export interface PublisherAudioIndex {
  source: { publisher: string; index: string; rights: string; retrieved: string };
  book: number;
  units: AudioUnit[];
}
